// src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {
  navs;

  constructor(
    private http: HttpClient
  ) { }

  ngOnInit() {
    this.navs = this.getNav();
  }

  getNav() {
    return this.http.get('/assets/json/nav.json');
  }

}

<nav class="navbar navbar-expand-lg navbar-toggleable-md navbar-light bg-light">
	<div class="container">
		<a class="navbar-brand text-primary" href="https://github.com/LYZhelloworld/lyzhelloworld.github.io" target="_blank">lyzhelloworld.github.io</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<!-- Template: Navbar -->
			<ul class="navbar-nav mr-auto">
				<li class="nav-item"
					*ngFor="let nav of navs | async"
					[routerLinkActive]="['active']"
					[routerLinkActiveOptions]="{exact:true}">
					<a class="nav-link" [routerLink]="[nav.href]">{{ nav.name }}<span class="sr-only"> (current)</span></a>
				</li>
			</ul>
			<!-- Template-end: Navbar -->
			<div>
				<a class="btn btn-outline-success" href="https://github.com/LYZhelloworld" target="_blank" aria-label="Follow @LYZhelloworld on GitHub">Follow @LYZhelloworld</a>
			</div>
		</div>
	</div>
</nav>

// src/components/controls/NavBar.vue
<template>
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="container">
      <a
        class="navbar-brand text-primary"
        href="https://github.com/LYZhelloworld/lyzhelloworld.github.io"
        target="_blank"
        rel="noopener noreferrer"
      >
        lyzhelloworld.github.io
      </a>
      <button
        class="navbar-toggler"
        data-bs-toggle="collapse"
        data-bs-target="#nav-collapse"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Right aligned nav items -->
      <div class="collapse navbar-collapse" id="nav-collapse">
        <ul class="navbar-nav me-auto">
          <li class="nav-item"><a class="nav-link active" href="#">Home</a></li>
        </ul>

        <div>
          <a
            class="btn btn-outline-success"
            href="https://github.com/LYZhelloworld"
            target="_blank"
            rel="noopener noreferrer"
            >Follow @LYZhelloworld</a
          >
        </div>
      </div>
    </div>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({});
</script>
