// src/components/Home.vue
<template>
  <div class="pt-5 bg-primary" style="height: 100%">
    <b-container fluid="" class="text-white text-center">
      <b-row>
        <b-col>
          <img src="@/assets/avatar.png" class="avatar fadein" alt="avatar"/>
        </b-col>
      </b-row>
      <b-row class="mt-4">
        <b-col>
          <p class="mb-4 display-4">Hello, world.</p>
          <b-button
              variant="success"
              class="mx-1"
              href="https://github.com/LYZhelloworld"
              target="_blank"
              rel="noopener noreferrer">
            View in GitHub
          </b-button>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script>
export default {
  name: "Home"
}
</script>

<style scoped>
.avatar {
  width: 100%;
  max-width: 200px;
  height: auto;
  border-radius: 50%;
  border: 5px solid #fff;
}

img.fadein {
  animation-name: fadein;
  animation-duration: 1s;
  -webkit-animation-name: fadein;
  -webkit-animation-duration: 1s;
  -moz-animation-name: fadein;
  -moz-animation-duration: 1s;
}

@keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@-webkit-keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@-moz-keyframes fadein {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
</style>

// src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  bodyTag: HTMLBodyElement = document.getElementsByTagName('body')[0];

  constructor() { }

  ngOnInit() {
    this.bodyTag.classList.add('bg-primary');
  }
  
  ngOnDestroy() {
    this.bodyTag.classList.remove('bg-primary');
  }

}

<div class="text-white mt-5">
	<div class="row text-center">
		<div class="col-sm-12">
			<img class="avatar" src="assets/img/avatar.png" />
		</div>
	</div>
	<div class="row mt-4 text-center">
		<div class="col-sm-12">
			<h2 class="mb-4">Helloworld</h2>
			<a class="btn btn-info mx-1" href="https://twitter.com/helloworld_twt" target="_blank">View in Twitter</a>
			<a class="btn btn-success mx-1" href="https://github.com/LYZhelloworld" target="_blank">View in GitHub</a>
		</div>
	</div>
</div>
